/* ASOC QUESTS // Shadow Broker contract console. Server owns every mutation. */
(() => {
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmtCoins = n => Number(n).toFixed(Number(n) % 1 ? 1 : 0);
  const fmtTime = ms => { const s=Math.max(0,Math.ceil(ms/1000)),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),ss=s%60; return d?`${d}d ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(ss).padStart(2,'0')}`:h?`${h}:${String(m).padStart(2,'0')}:${String(ss).padStart(2,'0')}`:`${m}:${String(ss).padStart(2,'0')}`; };
  const icon = (name,label='') => `<svg class="quest-icon quest-icon-${name}" viewBox="0 0 64 64"${label?` role="img" aria-label="${esc(label)}"`:' aria-hidden="true"'}><use href="assets/ui/quest-icons.svg#quest-${name}"></use></svg>`;
  const api = {
    state:{active:[],history:[],serverNow:Date.now()}, dailies:{players:[],serverNow:Date.now()}, tab:'create',
    send(type,payload={}) { window.App?.send?.({type,...payload}); },
    init() {
      document.getElementById('quests-btn')?.addEventListener('click',()=>this.open());
      setInterval(()=>this.renderCards(),1000);
      if (window.App?.questState) this.update(window.App.questState);
      if (window.App?.dailyState) this.updateDailies(window.App.dailyState);
    },
    ensure() {
      let root=document.getElementById('gm-quests-overlay'); if(root) return root;
      root=document.createElement('div'); root.id='gm-quests-overlay'; root.className='quests-overlay'; root.hidden=true;
      root.innerHTML=`<section class="quests-console"><div class="quest-console-crest">${icon('sigil','Shadow Broker contract ledger')}</div><header><div><small>SHADOW BROKER // CONTRACT LEDGER</small><h2>QUEST COMMAND</h2><p>Issue directives. Track oaths. Deliver judgment.</p></div><button data-q-close aria-label="Close quest command">×</button></header><nav><button data-q-tab="create">${icon('forge')}<span>FORGE CONTRACT</span></button><button data-q-tab="active">${icon('active')}<span>ACTIVE OATHS</span></button><button data-q-tab="archive">${icon('archive')}<span>ARCHIVE</span></button><button data-q-tab="dailies">${icon('daily')}<span>DAILY LEDGER</span></button></nav><div class="quests-body" data-q-body></div></section>`;
      document.body.appendChild(root);
      root.querySelector('[data-q-close]').onclick=()=>root.hidden=true;
      root.addEventListener('click',e=>{ const tab=e.target.closest('[data-q-tab]'); if(tab){this.tab=tab.dataset.qTab;this.render();} const action=e.target.closest('[data-q-action]'); if(action)this.act(action); });
      const syncDuration=e=>{const form=e.target.closest?.('[data-q-form]');if(!form||!e.target.matches('[name="durationValue"],[name="durationUnit"]'))return;const unit=Number(form.durationUnit.value),limits={60000:1440000,3600000:24000,86400000:1000};form.durationValue.max=String(limits[unit]||1000);form.durationMs.value=String(Math.round(Number(form.durationValue.value||0)*unit));form.querySelectorAll('[data-q-duration]').forEach(x=>x.classList.remove('selected'));};
      root.addEventListener('input',syncDuration);root.addEventListener('change',syncDuration);
      root.addEventListener('click',e=>{const button=e.target.closest('[data-q-duration]'),form=button?.closest('[data-q-form]');if(!form)return;const ms=Number(button.dataset.qDuration),unit=ms%86400000===0?86400000:ms%3600000===0?3600000:60000;form.durationUnit.value=String(unit);form.durationValue.value=String(ms/unit);form.durationValue.max=String(unit===86400000?1000:unit===3600000?24000:1440000);});
      return root;
    },
    open(){this.ensure().hidden=false;this.render();this.send('quest:sync');this.send('daily:sync');},
    update(msg){this.state={active:msg.active||[],history:msg.history||[],serverNow:msg.serverNow||Date.now()};this.render();},
    updateDailies(msg){this.dailies={players:msg.players||[],serverNow:msg.serverNow||Date.now()};if(this.tab==='dailies')this.render();},
    error(message){window.AsocDialog?.alert?.(String(message||'QUEST COMMAND REJECTED')) || alert(message);},
    players(){return (window.App?.currentPlayers||[]).filter(p=>p.connected!==false&&!p.isTestPersona&&p.id);},
    render(){const root=this.ensure(); root.querySelectorAll('[data-q-tab]').forEach(b=>b.classList.toggle('active',b.dataset.qTab===this.tab)); const body=root.querySelector('[data-q-body]'); if(this.tab==='create')body.innerHTML=this.createHTML();else if(this.tab==='dailies')body.innerHTML=this.dailiesHTML();else body.innerHTML='<div data-q-list></div>'; this.bindCreate(); this.renderCards();},
    dailiesHTML(){const players=this.dailies.players||[];if(!players.length)return `<div class="quest-empty">${icon('locked')}<b>THE LEDGER IS SILENT</b><span>NO AUTHENTICATED LITTLE HEROES ONLINE</span></div>`;const done=players.reduce((n,p)=>n+(p.completed||0),0),total=players.length*3,pct=Math.round(done/Math.max(1,total)*100);return `<div class="daily-gm-summary"><div><small>ROOM-WIDE COMPLETION</small><b>DAILY CONTRACT OVERSIGHT</b></div><strong>${done}<em>/ ${total}</em></strong><div class="daily-gm-meter"><i style="width:${pct}%"></i></div></div><div class="daily-gm-list">${players.map(p=>`<article class="daily-gm-player ${p.completed===p.total?'all-complete':''}"><header><div class="daily-player-sigil">${icon('sigil')}</div><div><small>LITTLE HERO</small><b>${esc(p.name)}</b></div><span>${p.completed||0}/${p.total||3}</span></header>${(p.contracts||[]).map(c=>`<div class="daily-gm-row ${c.complete?'complete':''}">${icon(c.complete?'complete':'active')}<span>${esc(c.title)}</span><b>${c.unit==='ms'?fmtTime(c.progress):`${c.progress}/${c.target}`}</b></div>`).join('')}<div class="daily-gm-bonus ${p.bonus?.complete?'complete':''}">${icon(p.bonus?.complete?'complete':'locked')} DAILY PURGE <b>${p.bonus?.complete?'CLAIMED':'LOCKED'}</b></div></article>`).join('')}</div>`;},
    createHTML(){return `<form class="quest-create" data-q-form><div class="quest-forge-intro">${icon('forge')}<div><small>NEW SHADOW CONTRACT</small><b>FORGE AN OATH</b><p>Bind one Little Hero to a directive, reward and deadline.</p></div></div><label><span>01 // CHOOSE THE BOUND</span><select name="targetPlayerId" required><option value="">SELECT ONLINE LITTLE HERO</option>${this.players().map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label><label><span>02 // INSCRIBE THE DIRECTIVE</span><textarea name="directive" maxlength="500" required placeholder="What must the Little Hero accomplish?"></textarea><small>BE PRECISE. THE CONTRACT RECORDS EXACT WORDING.</small></label><fieldset><legend>03 // SHADOW COIN BOUNTY</legend><div class="quest-presets">${[.5,1,2,3,5,10].map(n=>`<button type="button" data-q-reward="${n}">${icon('coin')}${n}</button>`).join('')}</div><input name="rewardCoins" type="number" min="0.1" max="50" step="0.1" value="3" required></fieldset><fieldset><legend>04 // OATH WINDOW</legend><div class="quest-presets">${[[1,'1m'],[5,'5m'],[15,'15m'],[1,'1h',3600000],[1,'1d',86400000],[7,'7d',604800000]].map(([n,l,ms])=>`<button type="button" data-q-duration="${ms||n*60000}">${l}</button>`).join('')}</div><div class="quest-duration-custom"><input name="durationValue" type="number" min="1" max="1440000" step="1" value="10" required aria-label="Custom quest duration"><select name="durationUnit" aria-label="Quest duration unit"><option value="60000">MINUTES</option><option value="3600000">HOURS</option><option value="86400000">DAYS</option></select></div><input name="durationMs" type="hidden" value="600000"><small>MANUAL OATH WINDOW // 1 MINUTE TO 1000 DAYS</small></fieldset><fieldset class="quest-visibility-field"><legend>05 // SEAL CLASSIFICATION</legend><div class="quest-visibility">${['PRIVATE','CLASSIFIED','PUBLIC'].map((v,i)=>`<label><input type="radio" name="visibility" value="${v}" ${i===0?'checked':''}>${icon(v.toLowerCase())}<span>${v}</span></label>`).join('')}</div></fieldset><button class="quest-issue" type="submit">${icon('sigil')} REVIEW &amp; SEAL CONTRACT</button><div data-q-confirm></div></form>`;},
    bindCreate(){const form=document.querySelector('[data-q-form]');if(!form)return;form.querySelectorAll('[data-q-reward]').forEach(b=>b.onclick=()=>{form.rewardCoins.value=b.dataset.qReward;form.querySelectorAll('[data-q-reward]').forEach(x=>x.classList.toggle('selected',x===b));});form.querySelectorAll('[data-q-duration]').forEach(b=>b.onclick=()=>{form.durationMs.value=b.dataset.qDuration;form.querySelectorAll('[data-q-duration]').forEach(x=>x.classList.toggle('selected',x===b));});form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));const player=this.players().find(p=>String(p.id)===data.targetPlayerId);const high=Number(data.rewardCoins)>10;form.querySelector('[data-q-confirm]').innerHTML=`<div class="quest-confirm ${high?'high-reward':''}"><div class="quest-wax-seal">${icon('sigil')}</div><small>FINAL CONTRACT REVIEW</small><h3>${high?'HIGH VALUE OATH':'SHADOW CONTRACT'}</h3><div class="quest-confirm-ledger"><span>BOUND <b>${esc(player?.name||'UNKNOWN')}</b></span><span>BOUNTY <b>${fmtCoins(data.rewardCoins)} SC</b></span><span>WINDOW <b>${fmtTime(data.durationMs)}</b></span><span>CLASS <b>${esc(data.visibility)}</b></span></div><blockquote>${esc(data.directive)}</blockquote><button type="button" data-q-send>ISSUE &amp; SEAL CONTRACT</button></div>`;form.querySelector('[data-q-send]').onclick=()=>{this.send('gm:questCreate',{...data,rewardCoins:Number(data.rewardCoins),durationMs:Number(data.durationMs)});this.tab='active';};};},
    card(q,archive=false){const remaining=q.deadline?fmtTime(q.deadline-Date.now()):'NOT STARTED';let actions='';if(!archive){if(q.status==='OFFERED')actions='<button class="danger" data-q-action="cancel">REVOKE</button>';if(q.status==='ACTIVE')actions='<button class="success" data-q-action="complete">MARK COMPLETE</button><button class="danger" data-q-action="fail">MARK FAILED</button><button data-q-action="cancel">REVOKE</button>';if(q.status==='CLAIMED')actions='<button class="success" data-q-action="complete">APPROVE CLAIM</button><button data-q-action="rejectClaim">RETURN TO HERO</button><button class="danger" data-q-action="fail">FAIL OATH</button><button data-q-action="cancel">REVOKE</button>';}const stateIcon=q.status==='COMPLETED'?'complete':['FAILED','EXPIRED','CANCELLED'].includes(q.status)?'failed':archive?'archive':'active';return `<article class="quest-card status-${q.status.toLowerCase()}" data-q-id="${esc(q.id)}"><div class="quest-card-rune">${icon(stateIcon)}</div><header><div><small>BOUND LITTLE HERO</small><b>${esc(q.targetPlayerName)}</b></div><span>${q.status}</span></header><p>${esc(q.directive)}</p><div class="quest-meta"><span>${icon('coin')}<b>${fmtCoins(q.rewardCoins)}</b> SHADOW COINS</span><span>${icon('time')}<b>${remaining}</b></span><span>${icon(String(q.visibility||'private').toLowerCase())}${q.visibility}</span></div>${archive?`<small class="quest-archive-stamp">CREATED ${new Date(q.createdAt).toLocaleString()} // RESOLVED ${new Date(q.resolvedAt).toLocaleString()}</small>`:`<div class="quest-actions">${actions}</div>`}</article>`;},
    renderCards(){const list=document.querySelector('#gm-quests-overlay [data-q-list]');if(!list)return;const rows=this.tab==='archive'?this.state.history:this.state.active;list.innerHTML=rows.length?rows.map(q=>this.card(q,this.tab==='archive')).join(''):'<div class="quest-empty">NO CONTRACTS IN THIS CHANNEL</div>';},
    act(button){const card=button.closest('[data-q-id]');const action=button.dataset.qAction;const type={complete:'gm:questComplete',rejectClaim:'gm:questRejectClaim',fail:'gm:questFail',cancel:'gm:questCancel'}[action];if(type)this.send(type,{questId:card.dataset.qId});}
  };
  window.GMQuests=api; document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>api.init()):api.init();
})();
