'use strict';
const assert=require('assert/strict'),fs=require('fs'),path=require('path');
const d=require('../dragon-raid');let checks=0;
const eq=(a,b,m)=>{checks++;assert.equal(a,b,m)};const ok=(v,m)=>{checks++;assert.ok(v,m)};
function raid(boss='varkhul',roles=['tank','heal','dps']){const r=d.createRaid(1000,boss);roles.forEach((role,i)=>d.join(r,{id:'p'+i,name:'P'+i},role));return r}

(()=>{const r=d.createRaid(1000,'varkhul');eq(r.phase,'RECRUITING');eq(r.dragonHp,100);eq(r.recruitEndsAt,121000);eq(r.boss.name,'Varkhul, the Ash Tyrant');eq(d.canStart(r),false);eq(d.join(r,{id:'a',name:'A'},'tank').ok,true);eq(r.participants.a.maxHp,15);eq(d.join(r,{id:'b',name:'B'},'heal').ok,true);eq(r.participants.b.resurrectionCharges,2);eq(d.join(r,{id:'c',name:'C'},'dps').ok,true);eq(d.canStart(r),true);eq(d.startBattle(r,2000).ok,true);eq(r.phase,'HERO_TURN');eq(r.activePlayerId,'a');eq(r.round,1);eq(r.battleEndsAt,602000)})();
(()=>{const r=raid();d.startBattle(r);let x=d.heroAction(r,'p1','attack','',20);eq(x.ok,false);x=d.heroAction(r,'p0','attack','',8);eq(x.damage,4);eq(r.dragonHp,96);eq(r.activePlayerId,'p1');eq(r.participants.p0.statuses.guard,0);x=d.heroAction(r,'p1','heal','p0',8);eq(x.healing,3);eq(r.activePlayerId,'p2');x=d.heroAction(r,'p2','rapid','',20);eq(x.damage,10);eq(r.phase,'BOSS_TURN');eq(r.participants.p2.cooldowns.rapid,2);x=d.bossAction(r,2,()=>0);eq(x.result,'miss');eq(x.damage,0);eq(r.phase,'HERO_TURN');eq(r.round,2);eq(r.participants.p2.cooldowns.rapid,1)})();
(()=>{const r=raid();d.startBattle(r);r.participants.p0.hp=10;let x=d.heroAction(r,'p0','shieldWall','',8);eq(x.ok,true);eq(r.participants.p0.shieldWall,0);eq(r.participants.p0.statuses.shieldWall,4);d.heroAction(r,'p1','attack','',1);d.heroAction(r,'p2','attack','',1);x=d.bossAction(r,4,()=>0);eq(x.result,'standard');eq(x.damage,0);eq(r.participants.p0.hp,10)})();
(()=>{const r=raid();d.startBattle(r);d.heroAction(r,'p0','attack','',1);r.participants.p2.hp=1;let x=d.heroAction(r,'p1','heal','p2',20);eq(x.healing,9);eq(r.participants.p2.hp,10);d.heroAction(r,'p2','attack','',1);d.bossAction(r,20,()=>.99);eq(r.participants.p2.alive,true);r.participants.p2.alive=false;r.participants.p2.hp=0;d.heroAction(r,'p0','attack','',1);x=d.heroAction(r,'p1','resurrect','p2',20);eq(x.revived,true);eq(x.refunded,true);eq(r.participants.p2.hp,3);eq(r.participants.p1.resurrectionCharges,2)})();
(()=>{const r=raid('varkhul',['dps','dps','dps']);d.startBattle(r);r.dragonHp=20;r.boss.hp=20;let x=d.heroAction(r,'p0','execute','',18);eq(x.damage,14);eq(r.dragonHp,6);eq(r.participants.p0.cooldowns.execute,3);eq(r.participants.p0.statuses.bloodlust,true);x=d.heroAction(r,'p1','attack','',20);eq(x.damage,13);eq(r.phase,'VICTORY')})();
(()=>{const r=d.createRaid(0,'deathwing');eq(r.dragonHp,150);eq(r.boss.heroic,true);['tank','heal','dps','dps'].forEach((role,i)=>d.join(r,{id:'x'+i,name:'X'},role));eq(d.canStart(r),false);ok(/EXACTLY FIVE/.test(d.startBattle(r).error));d.join(r,{id:'x4',name:'X'},'dps');eq(d.canStart(r),true);d.startBattle(r);r.phase='BOSS_TURN';let x=d.bossAction(r,3,()=>0);eq(x.result,'standard');r.phase='BOSS_TURN';r.dragonHp=99;x=d.bossAction(r,2,()=>0);eq(x.result,'miss');eq(r.boss.wrath,1);eq(r.worldBreaker,false)})();
(()=>{eq(d.weightedLoot(()=>.995),500);const s=d.splitLoot(307,['a','b','c','d'],()=>0);eq(Object.values(s).reduce((a,b)=>a+b,0),307);const h=d.heartRound(['a','b'],()=>.41);eq(h.winner,null);eq(h.tied.length,2);const pub=d.publicView(raid());eq(pub.participants.length,3);ok(!('_recruitTimer'in pub))})();
(()=>{const src=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8'),client=fs.readFileSync(path.join(__dirname,'..','js','dragon-raid.js'),'utf8'),html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');ok(/case 'dragon:action'/.test(src));ok(/case 'gm:dragonRaid'/.test(src));ok(!/name: '\/dragon'/.test(src));ok(/type: 'dragon:action'/.test(client));ok(/gm:dragonRaid/.test(client));ok(/dragon-raid-setup-btn/.test(html));ok(/ACTIVE HERO/.test(client))})();
ok(checks>=55,`expected at least 55 checks, got ${checks}`);
console.log(`dragon-raid tests: OK (${checks} checks)`);
