const assert = require('assert/strict');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const forge = fs.readFileSync(path.join(root, 'js', 'forge.js'), 'utf8');
const board = fs.readFileSync(path.join(root, 'js', 'board.js'), 'utf8');
const app = fs.readFileSync(path.join(root, 'js', 'app.js'), 'utf8');
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'css', 'forge-creator.css'), 'utf8');

assert.doesNotMatch(forge, /data-creator-field="title"/, 'creator no longer asks for a redundant title');
assert.match(forge, /d\.title = this\.isNew \? d\.theme/, 'new games derive their library title from the theme');
assert.match(forge, /FIELD_ORDER: \['A1'.*'finalSolution'\]/s, 'creator has a deterministic keyboard and paste order');
assert.match(forge, /click preview to jump/, 'creator explains click-to-focus navigation');
assert.match(forge, /data-creator-test/, 'creator exposes private test play');
assert.match(forge, /_testRevealed = new Set\(\)/, 'test play uses isolated reveal state');
assert.match(forge, /DRAFT_PREFIX: 'asoc_forge_draft:'/, 'creator autosaves browser-local drafts');
assert.match(forge, /PASTE WHOLE BOARD/, 'creator supports bulk board entry');
assert.match(forge, /creator-progress/, 'creator reports board completion');
assert.match(forge, /is-missing/, 'save validation visibly marks missing fields');
assert.match(forge, /is-long/, 'creator warns when board text has to shrink too far');
assert.match(forge, /cellHints/, 'unified editor retains prepared per-cell hints');
assert.match(board, /options\.revealed instanceof Set/, 'preview supports covered test-play cells');
assert.match(app, /PREPARED HINT \/\//, 'GM hint requests surface the prepared hint');
assert.match(index, /forge-creator\.css\?v=/, 'creator-specific styling is loaded and cache-busted');
assert.match(css, /#creator-board \.board-cell\.creator-focus/, 'focused field is visibly linked to its preview cell');
assert.match(css, /\.creator-paste-card/, 'bulk paste has a dedicated readable dialog');
assert.match(forge, /USE AS TEMPLATE/, 'library can create a clean board from an existing game');
assert.match(forge, /EXPORT \.XLSX/, 'library and editor expose spreadsheet export');
assert.match(forge, /data-creator-column-focus/, 'creator supports column-focused work');
assert.match(forge, /swapClueRows\(/, 'clue rows can be reordered by dragging');
assert.match(forge, /runQualityCheck\(/, 'creator provides one consolidated readiness audit');
assert.match(forge, /SUGGEST STRUCTURAL HINT/, 'creator can draft a safe structural hint');
assert.match(forge, /CTRL\+S SAVE · CTRL\+K COMMANDS/, 'keyboard-first creator shortcuts are visible');
assert.match(forge, /TEMPLATE_KEY: 'asoc_forge_templates:v1'/, 'reusable settings templates are browser-local and versioned');
assert.match(css, /\.creator-palette-card/, 'command palette has production styling');
assert.match(forge, /game-list-head/, 'library uses a compact labelled list instead of oversized cards');
assert.match(forge, /LAST UPDATED/, 'library exposes the saved date as a primary column');
assert.match(forge, /toLocaleDateString/, 'library renders compact human-readable dates');
assert.match(forge, /uppercaseCreatorInput\(field\)/, 'creator uppercases text at the point of entry');
assert.match(forge, /normalizeCreatorGame\(JSON\.parse/, 'loaded games and restored drafts are normalized to uppercase');
assert.match(forge, /this\.uppercaseCreatorText\(value\)\.slice\(0, 60\)/, 'bulk-pasted board cells are stored in uppercase');
assert.match(forge, /return this\.normalizeCreatorGame\(d\)/, 'saved creator data has an uppercase normalization safety barrier');
assert.match(index, /forge\.js\?v=20260928-creator-uppercase-1/, 'uppercase creator script is cache-busted');
assert.match(index, /asoc\.css\?v=20260928-quest-ledger-1/, 'compact library and contracts styling is cache-busted');

console.log('PASS ASOC Creator: theme identity, unified editor, guided entry, drafts, test play, fit warnings and prepared hints');
