'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const ROOT=path.join(__dirname,'..');
const css=fs.readFileSync(path.join(ROOT,'css','asoc.css'),'utf8');
const gm=fs.readFileSync(path.join(ROOT,'js','gm-quests.js'),'utf8');
const player=fs.readFileSync(path.join(ROOT,'js','player-quests.js'),'utf8');
const index=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');
const join=fs.readFileSync(path.join(ROOT,'join.html'),'utf8');

assert.match(gm,/QUEST COMMAND/,'GM console has the redesigned command-ledger masthead');
assert.match(gm,/FORGE AN OATH/,'contract creation has a guided forge hierarchy');
assert.match(gm,/quest-wax-seal/,'contract review has a ceremonial seal');
assert.match(gm,/daily-gm-meter/,'GM daily oversight has room-wide progress');
assert.match(player,/player-contract-scroll/,'player oath is rendered as a contract document');
assert.match(player,/quest-reward-panel/,'player contract separates bounty and deadline');
assert.match(player,/daily-contract-list/,'daily objectives use the redesigned ledger list');
assert.match(player,/OATH FULFILLED/,'daily completion has an explicit visual state');
assert.match(css,/QUEST LEDGER \/\/ ASOC occult-command visual system/,'quest visual system is present');
assert.match(css,/\.quest-card\.status-completed/,'completed contract state is styled');
assert.match(css,/\.quest-card\.status-failed/,'failed contract state is styled');
assert.match(css,/\.daily-contract\.complete/,'completed daily state is styled');
assert.match(css,/@media\(max-width:700px\)[\s\S]*?\.daily-contract\{grid-template-columns:42px 1fr/,'quest ledger has a compact narrow layout');
assert.match(css,/@media\(prefers-reduced-motion:reduce\)/,'quest motion respects reduced-motion preferences');
assert.match(index,/asoc\.css\?v=20260929-hint-column-1/,'GM loads the redesigned stylesheet immediately');
assert.match(index,/gm-quests\.js\?v=20260928-quest-ledger-1/,'GM quest client is cache-busted');
assert.match(join,/asoc\.css\?v=20260929-hint-column-1/,'player loads the redesigned stylesheet immediately');
assert.match(join,/player-quests\.js\?v=20260929-hardening-2/,'player quest client is cache-busted');
console.log('PASS quest visuals: GM forge, contract ledger, player oath, daily oversight, responsive states and reduced motion');
