'use strict';
const assert=require('node:assert/strict');
const rc=require('../roulette-carnage');
const table=rc.createTable('table-1','round-1',.5,1000);
assert.equal(table.round.phase,'TABLE_OPEN');
assert.equal(rc.validateBet({type:'STRAIGHT',value:0,amount:.5},.5).value,0);
assert.ok(rc.validateBet({type:'STRAIGHT',value:37,amount:1},.5).error);
assert.ok(rc.validateBet({type:'RED',amount:.4},.5).error);
assert.match(rc.validateBet({type:'RED',amount:.55},.5).error,/TENTHS/);
assert.deepEqual(rc.resolveBet({type:'STRAIGHT',value:0,amount:2},0),{won:true,odds:35,gross:72,label:'NUMBER 0'});
assert.equal(rc.resolveBet({type:'RED',amount:2},0).won,false);
assert.equal(rc.resolveBet({type:'RED',amount:2},3).gross,4);
assert.equal(rc.resolveBet({type:'LOW',amount:3},18).gross,6);
assert.equal(rc.resolveBet({type:'HIGH',amount:3},18).won,false);
table.round.joined.p1={id:'p1',name:'ONE'};table.round.joined.p2={id:'p2',name:'TWO'};
table.round.wagers=[{id:'w1',playerId:'p1',playerName:'ONE',type:'STRAIGHT',value:0,amount:1},{id:'w2',playerId:'p2',playerName:'TWO',type:'BLACK',value:null,amount:2}];
assert.equal(rc.isZeroImmune(table.round.wagers,'p1',0),true);assert.equal(rc.isZeroImmune(table.round.wagers,'p2',0),false);
const player=rc.view(table,'p1',false,9);assert.equal(player.ownWagers.length,1);assert.equal(player.wagers,undefined);assert.equal(player.balance,9);
const gm=rc.view(table,'__GM__',true);assert.equal(gm.wagers.length,2);assert.equal(gm.activePlayers,2);assert.equal(gm.zeroPlayers,1);
table.round.phase='SPINNING';table.round.winningNumber=17;assert.equal(rc.view(table,'p1',false,9).result,null);
table.round.phase='RESULT';assert.equal(rc.view(table,'p1',false,9).result,17);
console.log('PASS Roulette Carnage rules: conventional bets, zero immunity, private projections and GM oversight');
